export const SUBMIT_CATEGORY_REQUESTED = 'SUBMIT_CATEGORY_REQUESTED';
export const FETCH_CATEGORY_REQUESTED = 'FETCH_CATEGORY_REQUESTED';
export const FETCH_CATEGORY_SUCCEEDED = 'FETCH_CATEGORY_SUCCEEDED';
export const FETCH_CATEGORIES_SUCCEEDED = 'FETCH_CATEGORIES_SUCCEEDED';
export const DELETE_CATEGORY_REQUESTED = 'DELETE_CATEGORY_REQUESTED';
export const CLEAN_CATEGORY_FORM = 'CLEAN_CATEGORY_FORM';
