export const SUBMIT_ACTIVITY_REQUESTED = 'SUBMIT_ACTIVITY_REQUESTED';
export const FETCH_ACTIVITY_SUCCEEDED = 'FETCH_ACTIVITY_SUCCEEDED';
export const FETCH_ACTIVITIES_REQUESTED = 'FETCH_ACTIVITIES_REQUESTED';
export const FETCH_ACTIVITIES_SUCCEEDED = 'FETCH_ACTIVITIES_SUCCEEDED';
export const DELETE_ACTIVITY_REQUESTED = 'DELETE_ACTIVITY_REQUESTED';
export const CLEAN_ACTIVITY_FORM = 'CLEAN_ACTIVITY_FORM';
