export const SUBMIT_CONTACT_REQUESTED = 'SUBMIT_CONTACT_REQUESTED';
export const FETCH_CONTACT_SUCCEEDED = 'FETCH_CONTACT_SUCCEEDED';
export const FETCH_CONTACTS_REQUESTED = 'FETCH_CONTACTS_REQUESTED';
export const FETCH_CONTACTS_SUCCEEDED = 'FETCH_CONTACTS_SUCCEEDED';
export const DELETE_CONTACT_REQUESTED = 'DELETE_CONTACT_REQUESTED';
export const CLEAN_REGISTER_FORM = 'CLEAN_REGISTER_FORM';
