export const SUBMIT_NEWS_REQUESTED = 'SUBMIT_NEWS_REQUESTED';
export const FETCH_NEWS_REQUESTED = 'FETCH_NEWS_REQUESTED';
export const FETCH_ONE_NEWS_SUCCEEDED = 'FETCH_ONE_NEWS_SUCCEEDED';
export const FETCH_NEWS_SUCCEEDED = 'FETCH_NEWS_SUCCEEDED';
export const DELETE_NEWS_REQUESTED = 'DELETE_NEWS_REQUESTED';
export const CLEAN_NEWS_FORM = 'CLEAN_NEWS_FORM';
