export const FETCH_MEMBER_SUCCEEDED = 'FETCH_MEMBER_SUCCEEDED';
export const FETCH_MEMBERS_REQUESTED = 'FETCH_MEMBERS_REQUESTED';
export const FETCH_MEMBERS_SUCCEEDED = 'FETCH_MEMBERS_SUCCEEDED';
export const SUBMIT_MEMBER_REQUESTED = 'SUBMIT_MEMBER_REQUESTED';
export const DELETE_MEMBER_REQUESTED = 'DELETE_MEMBER_REQUESTED';
export const CLEAN_MEMBER_FORM = 'CLEAN_NEWS_FORM';
