export const FETCH_ORGANIZATION_REQUESTED = 'FETCH_ORGANIZATION_REQUESTED';
export const FETCH_ORGANIZATION_SUCCEEDED = 'FETCH_ORGANIZATION_SUCCEEDED';
export const FETCH_ORGANIZATIONS_REQUESTED = 'FETCH_ORGANIZATIONS_REQUESTED';
export const FETCH_ORGANIZATIONS_SUCCEEDED = 'FETCH_ORGANIZATIONS_SUCCEEDED';
export const FETCH_ORGANIZATIONFORM_SUCCEEDED = 'FETCH_ORGANIZATIONFORM_SUCCEEDED';
export const CLEAN_ORGANIZATION_FORM = 'CLEAN_ORGANIZATION_FORM';
export const SUBMIT_ORGANIZATION_REQUESTED = 'SUBMIT_ORGANIZATION_REQUESTED';
export const DELETE_ORGANIZATION_REQUESTED = 'DELETE_ORGANIZATION_REQUESTED';
