export const SUBMIT_USER_REQUESTED = 'SUBMIT_USER_REQUESTED';
export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED';
export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const CLEAN_REGISTER_FORM = 'CLEAN_REGISTER_FORM';
