export const SUBMIT_TESTIMONIAL_REQUESTED = 'SUBMIT_TESTIMONIAL_REQUESTED';
export const FETCH_TESTIMONIAL_REQUESTED = 'FETCH_TESTIMONIAL_REQUESTED';
export const FETCH_TESTIMONIAL_SUCCEEDED = 'FETCH_TESTIMONIAL_SUCCEEDED';
export const FETCH_TESTIMONIALS_REQUESTED = 'FETCH_TESTIMONIALS_REQUESTED';
export const FETCH_TESTIMONIALS_SUCCEEDED = 'FETCH_TESTIMONIALS_SUCCEEDED';
export const DELETE_TESTIMONIAL_REQUESTED = 'DELETE_TESTIMONIAL_REQUESTED';
export const CLEAN_REGISTER_FORM = 'CLEAN_REGISTER_FORM';
